### ISSUE TITLE
https 下 bug？

### ISSUE THREAD

**Issue by ahrime** [blinkfox/ghost-matery2#1]
在https下返回顶部和'<'' >'变为不可见了，在http下没问题，，，不懂js，不知道是怎么回事，应该是bug吧
[这是我的](https://ahri.ml)

**Comment by blinkfox** [comment]
@ahrime 这个是因为在https下没有加载[http://cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css](http://cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css)的引起的.

你可以在`default.hbs`文件中把`fontawesome`和`jquery`两个用到bootcdn的地方的`http:`字样去掉即可，即改成如下就可以了：

图标字体fontawesome的cdn修改：

``` html
<link type="text/css" rel="stylesheet" href="//cdn.bootcss.com/font-awesome/4.5.0/css/font-awesome.min.css">
<script type="text/javascript" src="//cdn.bootcss.com/jquery/2.2.0/jquery.min.js"></script>
```

或者，可以再接再http后加个`s`，如果想调用自己服务器的，就把这两个加载改成这样都可以吧

```
<link type="text/css" rel="stylesheet" href="{{assets/plugins/awesome/css/font-awesome.min.css}}" />
```
