### ISSUE TITLE
请支持ghostblog 1.x

### ISSUE THREAD

**Issue by abbycin** [blinkfox/ghost-matery2#13]
![screenshot_20180219_102340](https://user-images.githubusercontent.com/6814167/36360455-fc96cd78-155e-11e8-9237-555af0a3edff.png)

在ghostblog 1.x上试图使用ghost-matery2出现的错误。能支持1.x吗？ 谢谢！

**Comment by blinkfox** [comment]
@abbycin 嗯，过几天我看看，春节期间太忙了，没法碰电脑。估计是比较新版本的ghost版本有些标签不支持了

**Comment by abbycin** [comment]
@blinkfox 我按照提示的修改后可以使用了， 但是分页又有问题，之前0.1x的时候设置的是每页6个文章，现在变成了每页5个，还有个占位符（随机的出现在各个位置），具体现象麻烦到 [https://note.isliberty.me](https://note.isliberty.me)看看。

谢谢！

**Comment by blinkfox** [comment]
@abbycin 我把本主题在新版本中你提到的问题都修改了，1.x新版本设置分页是在主题文件目录中的`package.json`中，比如设置每页显示六条博文列表的方式如下：
```javascript
"config": {
    "posts_per_page": 6
}
```

我博客的版本还是0.7.4的版本，目前ghost1.21.2的版本相比以前，已经新增了很多标签和功能了，后续我再回再加入一些新版本展示的功能。
