### ISSUE TITLE
上下两个帖子重合在一起了

### ISSUE THREAD

**Issue by abbycin** [blinkfox/ghost-matery2#14]
如图
![screenshot_20180513_224617](https://user-images.githubusercontent.com/6814167/39968492-21d3d7d8-5700-11e8-818e-feb4c35ffbe2.jpg)

我猜测是因为图中第一个帖子里面用到了MathJax导致这个问题，那么怎么解决呢？ 
谢谢！

**Comment by blinkfox** [comment]
@abbycin 你好，你把主题中的`partials/loop.hbs`文件，用来显示摘要的这块儿代码

```html
<p>{{excerpt characters="120"}}</p>
```

把其中的`<p>`标签改成用`<div>`标签来包裹，改成如下的代码试试：

```html
<div>{{excerpt characters="120"}}</div>
```

**Comment by abbycin** [comment]
没有变化，只是改变窗口大小时会恢复正常，但是点刷新后又变回老样子了。

**Comment by blinkfox** [comment]
@abbycin 我刚刚在本地搭建了最新版的Ghost，引入了MathJax的插件，重现了你的问题。由于显示了数学公式，MathJax插入了一些它里面的必要的的html元素，且文章摘要字数是固定的120个字符，导致瀑布流的布局占据了很多高度。

目前想到的一个比较好的方案是，你把`default.hbs`文件中的MathJax插件删掉，将其移到放置在`post.hbs`文件的最下面，这样只有在加载和查看文章时才显示数学公式，在瀑布流里面不显示公式，这样可以解决你的问题。

**Comment by abbycin** [comment]
@blinkfox 好的， 我一会儿试试

**Comment by abbycin** [comment]
是可以解决，不过是牺牲了预览而已，可以接受，感谢巨佬！
