### ISSUE TITLE
左上角的设置按钮能不能别让它转了，强迫症受不了了

### ISSUE THREAD

**Issue by HelloVass** [blinkfox/ghost-matery2#2]
我非常喜欢作者的主题，
然而左上角的**设置**按钮什么鬼？
一直在模仿菊花转啊转的行为
不知道的还以为一直处于加载中呢！
求作者更新下

**Comment by blinkfox** [comment]
@HelloVass 哈哈！不能让它转，很简单啊！在`partials/theme_change.hbs`文件中找到`fa-spin`这个样式名称，去掉这几个字母就行。
如果，不想要这个功能，在`default.hbs`文件中去掉`{{> theme_change}}`这句就行，或者隐藏掉这个切换按钮也行！

**Comment by HelloVass** [comment]
@blinkfox 阿里嘎多，我还以为有生之年都得不到回复了呢！

**Comment by hao-lee** [comment]
一开始觉得没什么，看多了。。。嗯。。。我还是让它停下吧。。。

**Comment by blinkfox** [comment]
@kerneldeveloper 嗯，前面有让它停的方法说明，你看看！

**Comment by hao-lee** [comment]
我已经让它消失了~感觉显示个齿轮还是挺突兀的

**Comment by blinkfox** [comment]
嗯，好的，本来就是没太大作用，好玩的功能吧
