### ISSUE TITLE
关于社交化分享的定制

### ISSUE THREAD

**Issue by HelloVass** [blinkfox/ghost-matery2#3]
## 弹出的这个 Dialog 该如何修改

<img src="https://cloud.githubusercontent.com/assets/11362205/15014893/27956ff8-123b-11e6-9a12-e3887b1efa86.png" width="480px" height="960px"/>

很纠结啊，按照 README 里的修改了**社交化分享**，也确实生效了！但是，在移动端使用的时候，突然发现这个 `share dialog` 里的分享并没有改变，目前我只想分享到**微博、微信**平台，想请教下作者，该如何修改呢？

**Comment by blinkfox** [comment]
@HelloVass 关于移动端这个分享的页在`partials/mobile_share.hbs`文件中，你可以修改它就行！

**Comment by HelloVass** [comment]
thanks，但是，我并不知道这怎么改？跟 `post.hbs` 里不太一样，我找不到那些 `<a />` 标签哎，不过谢谢作者回复这么快，我找童鞋问问！

**Comment by blinkfox** [comment]
这个调的是第三方的分享插件，[JiaThis](http://www.jiathis.com/)
