### ISSUE TITLE
Markdown列表不显示

### ISSUE THREAD

**Issue by abbycin** [blinkfox/ghost-matery2#4]
更换这个主题后，发现之前的列表都不显示了
之前Casper主题显示是这样
![xx2](https://cloud.githubusercontent.com/assets/6814167/15217563/a1a71b08-188e-11e6-8617-0cae7e62c109.png)

而这个主题显示是这样  
![xx1](https://cloud.githubusercontent.com/assets/6814167/15217577/c843cb94-188e-11e6-840a-46b0a5a71e9e.png)  

编辑器中是这样  
![xx](https://cloud.githubusercontent.com/assets/6814167/15217587/d6c60aec-188e-11e6-9316-1a26a7cf53f1.png)

**请问是哪里出了问题？如何解决？**

**Comment by blinkfox** [comment]
@abbycin  列表没有加样式吧，我这两天之内抽空改改！

**Comment by blinkfox** [comment]
@abbycin 谢谢你的反馈，已修改无序列的显示问题，你可以下载最新版试试，或者只替换`assets/css/screen.css`这个样式文件即可！

**Comment by abbycin** [comment]
非常感谢，已经弄好了！
