### ISSUE TITLE
时间归档问题

### ISSUE THREAD

**Issue by hao-lee** [blinkfox/ghost-matery2#5]
这主题太棒了~感谢作者的付出~
请问可以实现按时间年月归档嘛，有时候按照时间看看自己以前的博文还是很有感触的~

**Comment by blinkfox** [comment]
@kerneldeveloper 
不行，ghost本身没有提供这样的接口，主题就不能读到这些数据，更专注于内容吧，估计ghost以后会提供这样的功能吧，到时候再添加

**Comment by hao-lee** [comment]
@blinkfox 原来如此，多谢~
