### ISSUE TITLE
页面最下方的字体颜色如何更改

### ISSUE THREAD

**Issue by hao-lee** [blinkfox/ghost-matery2#7]
> 本站由©Blinkfox基于 Ghost 采用 ghost-matery2主题搭建.

这一行如何更改字体颜色，我把页面背景色换成草绿色了，结果这些字体看不清楚。。。。。。

**Comment by blinkfox** [comment]
@kerneldeveloper 修改字体的样式即可，修改的文件在`assets\css\screen.css`文件中391行的链接颜色就行，尾部的样式都可以在这里修改或新增

**Comment by hao-lee** [comment]
nice,感谢~
