### ISSUE TITLE
怎样解决点击链接总是在新标签页打开？

### ISSUE THREAD

**Issue by abbycin** [blinkfox/ghost-matery2#8]
问题是这样的，我想做页内跳转，比如这样:

```
<a href="#1">右值引用</a>
<a href="#2">移动语义</a>
<a href="#3">完美转发</a>
....
....
[右值引用](#1)
....
....
[移动语义](#2)
....
....
[完美转发](#3)
```

但是点击链接总是在新标签页打开，即使加上了`target='_self'`也是这样。

那么我想知道，使用这个主题的话页内跳转该怎么做？谢谢！

**Comment by blinkfox** [comment]
@abbycin 你可以在`assets/js/index.js`文件中第 70 行，去掉`.attr('target', '_blank')`这部分代码即可
